spring.application.name=bookhunt

brevo.api.key=${BREVO_API_KEY}

# Database connection (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/bookhunt
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update